FROM resin/rpi-raspbian:jessie


ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 6.7.0
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl xz-utils

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-armv7l.tar.gz" \
  && tar -xzf "node-v$NODE_VERSION-linux-armv7l.tar.gz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-armv7l.tar.gz"

ADD package.json package.json
RUN npm install
ADD . .

RUN npm install && npm run clean

LABEL databox.type="store"

EXPOSE 8080

CMD ["npm","start"]